[workspace]
members = [
    "crates/server",
    "crates/client",
    "crates/cli",
]
resolver = "3"

[workspace.package]
edition = "2024"
license = "AGPL-3.0"
version = "0.1.0"
authors = ["Kevin Stock"]

[workspace.dependencies]
client = { path = "crates/client" }
